# Generated by Django 5.1.15 on 2026-08-15 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Nl2SqlExperiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parameters', models.JSONField(default=dict)),
                ('schema_snapshot', models.TextField(blank=True)),
                ('prompt_sample', models.TextField(blank=True)),
                ('question_count', models.IntegerField(default=0)),
                ('scored', models.IntegerField(default=0)),
                ('executed', models.IntegerField(default=0)),
                ('correct', models.IntegerField(default=0)),
                ('gold_failed', models.IntegerField(default=0)),
                ('execution_accuracy', models.FloatField(default=0.0)),
                ('valid_sql_rate', models.FloatField(default=0.0)),
                ('by_tag', models.JSONField(default=dict)),
                ('by_error_kind', models.JSONField(default=dict)),
                ('prompt_tokens', models.IntegerField(default=0)),
                ('completion_tokens', models.IntegerField(default=0)),
                ('elapsed_sec', models.FloatField(default=0.0)),
                ('aborted', models.BooleanField(default=False)),
                ('abort_reason', models.TextField(blank=True)),
                ('is_starred', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'nl2sql_experiment',
                'ordering': ['-id'],
            },
        ),
    ]
