# Generated by Django 5.1.15 on 2026-08-17 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nl2sql', '0002_nl2sqlexperiment_dataset_digest_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nl2SqlStage2Experiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parameters', models.JSONField(default=dict)),
                ('dataset_digest', models.CharField(blank=True, max_length=64)),
                ('dataset_path', models.CharField(blank=True, max_length=300)),
                ('question_count', models.IntegerField(default=0)),
                ('judged', models.IntegerField(default=0)),
                ('failed', models.IntegerField(default=0)),
                ('tp', models.IntegerField(default=0)),
                ('fn', models.IntegerField(default=0)),
                ('fp', models.IntegerField(default=0)),
                ('tn', models.IntegerField(default=0)),
                ('axis2_scored', models.IntegerField(default=0)),
                ('axis2_keyword_match', models.IntegerField(default=0)),
                ('axis2_human_reviewed', models.IntegerField(default=0)),
                ('axis2_human_correct', models.IntegerField(default=0)),
                ('axis2_disagreement', models.IntegerField(default=0)),
                ('prompt_tokens', models.IntegerField(default=0)),
                ('completion_tokens', models.IntegerField(default=0)),
                ('elapsed_sec', models.FloatField(default=0.0)),
                ('aborted', models.BooleanField(default=False)),
                ('abort_reason', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'nl2sql_stage2_experiment',
                'ordering': ['-id'],
            },
        ),
    ]
