# Generated by Django 5.1.15 on 2026-08-19 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nl2sql', '0003_nl2sqlstage2experiment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nl2SqlStage2RuleExperiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parameters', models.JSONField(default=dict)),
                ('dataset_digest', models.CharField(blank=True, max_length=64)),
                ('dataset_path', models.CharField(blank=True, max_length=300)),
                ('question_count', models.IntegerField(default=0)),
                ('judged', models.IntegerField(default=0)),
                ('failed', models.IntegerField(default=0)),
                ('type1_detected', models.IntegerField(default=0)),
                ('type2_detected', models.IntegerField(default=0)),
                ('type3_detected', models.IntegerField(default=0)),
                ('type4_detected', models.IntegerField(default=0)),
                ('needs_clarification_count', models.IntegerField(default=0)),
                ('prompt_tokens', models.IntegerField(default=0)),
                ('completion_tokens', models.IntegerField(default=0)),
                ('elapsed_sec', models.FloatField(default=0.0)),
                ('aborted', models.BooleanField(default=False)),
                ('abort_reason', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'nl2sql_stage2_rule_experiment',
                'ordering': ['-id'],
            },
        ),
    ]
