# Generated by Django 5.1.15 on 2026-08-20 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nl2sql', '0004_nl2sqlstage2ruleexperiment'),
    ]

    operations = [
        migrations.AddField(
            model_name='nl2sqlstage2ruleexperiment',
            name='prompt_digest',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
