# Generated by Django 5.1.15 on 2026-08-20 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nl2sql', '0005_nl2sqlstage2ruleexperiment_prompt_digest'),
    ]

    operations = [
        migrations.AddField(
            model_name='nl2sqlstage2ruleexperiment',
            name='flag_prompt_digest',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
